# Generated by Django 5.0.4 on 2024-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quote',
            field=models.TextField(null=True),
        ),
    ]
