# Generated by Django 5.0.4 on 2024-04-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
