# Generated by Django 5.0.4 on 2024-04-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imglist',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
