# Generated by Django 5.0.4 on 2024-05-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comments_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='active',
        ),
    ]
