# Generated by Django 5.0.4 on 2024-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_comments_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
