# Generated by Django 5.0.4 on 2024-05-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_comments_article_alter_comments_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
